package ch.bfh.btx8081.weiss.model;

import java.time.LocalDate;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * The Class Patient represents the patient entity. A patient is a Person which receives medical
 * healthcare from a doctor or therapist.
 */
@Entity
public class Patient {
	
	/** The patient id. */
	@Id
	@GeneratedValue(strategy = GenerationType.TABLE)
	private int patientID = 0;

	/** The appointments for this patient. */
	@OneToMany(mappedBy = "patient")
	private List<Appointment> appointments = null;
	
	/** The medications for this patient. */
	//Eager loading for being able to display stuff with toString(), without explicitly loading 
	@OneToMany(mappedBy = "patient",  fetch=FetchType.EAGER)
	private List<Medication> medication = null;

	/** The picture of this patient. */
	private String picture = null; // base64
	
	/** The first name of this patient. */
	private String firstName = null;
	
	/** The last name of this patient. */
	private String lastName = null;
	
	/** The eMail of this patient. */
	private String eMail = null;
	
	/** The gender of this patient. */
	private String gender = null;
	
	/** The street of this patient. */
	private String street = null;
	
	/** The ZIP of the city. */
	private String zip = null;
	
	/** The city where the patient lives. */
	private String city = null;
	
	/** The ssn of this patient. */
	private String ssn = null;
	
	/** The birthday of this patient. */
	private LocalDate birthday = null;
	
	/** The self harm status of this patient. */
	private int harmID = 0;

	/**
	 * Instantiates a new patient.
	 */
	public Patient() {
	}

	/**
	 * Instantiates a new patient.
	 *
	 * @param id
	 *            the id
	 */
	public Patient(int id) {
		this.patientID = id;
	}

	// autogenerated

	/**
	 * Gets the patient id.
	 *
	 * @return the patient id
	 */
	public int getPatientID() {
		return patientID;
	}

	/**
	 * Gets the first name.
	 *
	 * @return the first name
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * Gets the last name.
	 *
	 * @return the last name
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * Gets the e mail.
	 *
	 * @return the e mail
	 */
	public String geteMail() {
		return eMail;
	}

	/**
	 * Gets the gender.
	 *
	 * @return the gender
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * Gets the street.
	 *
	 * @return the street
	 */
	public String getStreet() {
		return street;
	}

	/**
	 * Gets the zip.
	 *
	 * @return the zip
	 */
	public String getZip() {
		return zip;
	}

	/**
	 * Gets the city.
	 *
	 * @return the city
	 */
	public String getCity() {
		return city;
	}

	/**
	 * Gets the ssn.
	 *
	 * @return the ssn
	 */
	public String getSsn() {
		return ssn;
	}

	/**
	 * Gets the birthday.
	 *
	 * @return the birthday
	 */
	public LocalDate getBirthday() {
		return birthday;
	}

	/**
	 * Gets the harm id.
	 *
	 * @return the harm id
	 */
	public int getHarmID() {
		return harmID;
	}

	/**
	 * Gets the picture.
	 *
	 * @return the picture
	 */
	public String getPicture() {
		return picture;
	}
	
	/**
	 * Gets the appointments.
	 *
	 * @return the appointments
	 */
	public List<Appointment> getAppointments() {
		return appointments;
	}
	
	/**
	 * Sets the patient id.
	 *
	 * @param patientID
	 *            the new patient id
	 */
	public void setPatientID(int patientID) {
		this.patientID = patientID;
	}

	/**
	 * Sets the first name.
	 *
	 * @param firstName
	 *            the new first name
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * Sets the last name.
	 *
	 * @param lastName
	 *            the new last name
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/**
	 * Sets the e mail.
	 *
	 * @param eMail
	 *            the new e mail
	 */
	public void seteMail(String eMail) {
		this.eMail = eMail;
	}

	/**
	 * Sets the gender.
	 *
	 * @param gender
	 *            the new gender
	 */
	public void setGender(String gender) {
		this.gender = gender;
	}

	/**
	 * Sets the street.
	 *
	 * @param street
	 *            the new street
	 */
	public void setStreet(String street) {
		this.street = street;
	}

	/**
	 * Sets the zip.
	 *
	 * @param zip
	 *            the new zip
	 */
	public void setZip(String zip) {
		this.zip = zip;
	}

	/**
	 * Sets the city.
	 *
	 * @param city
	 *            the new city
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * Sets the ssn.
	 *
	 * @param ssn
	 *            the new ssn
	 */
	public void setSsn(String ssn) {
		this.ssn = ssn;
	}

	/**
	 * Sets the birthday.
	 *
	 * @param birthday
	 *            the new birthday
	 */
	public void setBirthday(LocalDate birthday) {
		this.birthday = birthday;
	}

	/**
	 * Sets the harm id.
	 *
	 * @param harmID
	 *            the new harm id
	 */
	public void setHarmID(int harmID) {
		this.harmID = harmID;
	}

	/**
	 * Sets the picture.
	 *
	 * @param picture
	 *            the new picture
	 */
	public void setPicture(String picture) {
		this.picture = picture;
	}

	/**
	 * Gets the medication.
	 *
	 * @return the medication
	 */
	public List<Medication> getMedication() {
		return medication;
	}

	/**
	 * Sets the appointments.
	 *
	 * @param appointments
	 *            the new appointments
	 */
	public void setAppointments(List<Appointment> appointments) {
		this.appointments = appointments;
	}

	/**
	 * Sets the medication.
	 *
	 * @param medication
	 *            the new medication
	 */
	public void setMedication(List<Medication> medication) {
		this.medication = medication;
	}
}
