package ch.bfh.btx8081.weiss.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.ListSelect;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MedicationPrescriptionView extends HorizontalLayout {
	protected Label medication;
	protected ListSelect drugList;
	protected Button btnCompendium;
	protected Button btnDaily1;
	protected Button btnDaily2;
	protected Button btnDaily3;
	protected Button btnDaily4;
	protected Button btnDaily6;
	protected Button btnDaily8;
	protected Button btnDaily12;
	protected Button btnMon;
	protected Button btnTue;
	protected Button btnWed;
	protected Button btnThu;
	protected Button btnFri;
	protected Button btnSat;
	protected Button btnSun;
	protected Button btnWeeks1;
	protected Button btnWeeks2;
	protected Button btnWeeks3;
	protected Button btnWeeks4;
	protected Button btnWeeks5;
	protected Button btnWeeks6;
	protected Button btnWeeksInfinitely;
	protected Label lblDose;
	protected Button btnDose7;
	protected Button btnDose8;
	protected Button btnDose9;
	protected Button btnDose4;
	protected Button btnDose5;
	protected Button btnDose6;
	protected Button btnDose1;
	protected Button btnDose2;
	protected Button btnDose3;
	protected Button btnDose0;
	protected Button btnDosePoint;
	protected Button btnDoseBackspace;
	protected ListSelect unitList;
	protected Button btnPrescripe;

	public MedicationPrescriptionView() {
		Design.read(this);
	}
}
