package ch.bfh.btx8081.weiss.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class SOAPDetailComponent extends HorizontalLayout {
	protected Label entryDate;
	protected Label subjectiveText;
	protected Label objectiveText;
	protected Label assessmentText;
	protected Label planText;

	public SOAPDetailComponent() {
		Design.read(this);
	}
}
